on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    #1 build - tests
  build:
    uses: MigracaoDotNetForms/ci-cd-pipelines/.github/workflows/reusable-build.yml@main
    with:
      solution_name: 'Projeto_ClassLibrary.sln'
      build_configuration: 'Release'
      test_path: 'Projeto_ClassLibrary.Tests/bin/Release/net6.0/Projeto_ClassLibrary.Tests.dll'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      

     #3 deploy
  deploy:
    needs: test
    uses: MigracaoDotNetForms/ci-cd-pipelines/.github/workflows/package-deploy.yml@main
    with:
      build_configuration: 'Release'
      project_path: 'Projeto_ClassLibrary/Projeto_ClassLibrary.csproj'
